apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: patches/service_port_5432.yaml
  target:
    kind: Service
    name: postgres-operator
- path: patches/config_api_port_5432.yaml
  target:
    kind: ConfigMap
    name: postgres-operator

# patchesStrategicMerge:
# - patches/config_api_port_5432.yaml

# secretGenerator:
# - name: dbpass
#   files:
#     - dbpass.txt

# patchesStrategicMerge:
# - configmap.yaml

# patchesJson6902:
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: example
#   path: deployment.yaml

# resources:
# - vendored/manifests/kustomization.yaml

# Apply the manifests in the following order
# 1 of 2 mutually exclusive ways to set-up Postgres Operator
# resources:
# - vendored/manifests/operatorconfiguration.crd.yaml
# - vendored/manifests/postgresql-operator-default-configuration.yaml
# - vendored/manifests/operator-service-account-rbac.yaml
# - vendored/manifests/postgres-operator.yaml

# Apply the manifests in the following order
# 2 of 2 mutually exclusive ways to set-up Postgres Operator
# TODO: Move RBAC stuff to the kube-system namespace
resources:
- vendored/manifests/configmap.yaml
- vendored/manifests/operator-service-account-rbac.yaml
- vendored/manifests/postgres-operator.yaml
- vendored/manifests/api-service.yaml
