patches:
- path: patches/deployment_hydra_force_insecure.yaml
  target:
    kind: Deployment
    namespace: demandcluster
    name: hydra-deployment
- path: patches/ingress_disable_tls.yaml
  target:
    kind: Ingress
    namespace: demandcluster

configMapGenerator:
- name: hydra-env-config
  files:
  - config/hydra.properties
- name: api-env-config
  files:
  - config/api.properties
- name: identity-env-config
  files:
  - config/identity.properties
- name: admin-env-config
  files:
  - config/admin.properties
- name: storefront-env-config
  files:
  - config/storefront.properties

secretGenerator:
- name: hydra-env-secrets
  literals:
  - DSN=postgres://hydra:changeme@reaction-postgresql-headless:5432/hydra?sslmode=disable
  - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
  - SECRETS_SYSTEM=youReallyNeedToChangeThis
- name: api-env-secrets
  literals:
  - MONGO_URL=mongodb://root:reaction-mongodb-headless:27017/reaction?replicaSet=rs0&authSource=admin
  - STRIPE_API_KEY=YOUR_PRIVATE_STRIPE_API_KEY
- name: identity-env-secrets
  literals:
  - MONGO_OPLOG_URL=mongodb://reaction-mongodb-headless:27017/local
  - MONGO_URL=mongodb://reaction-mongodb-headless:27017/reaction
- name: admin-env-secrets
  literals:
  - MONGO_OPLOG_URL=mongodb://reaction-mongodb-headless:27017/local
  - MONGO_URL=mongodb://reaction-mongodb-headless:27017/reaction
- name: storefront-env-secrets
  literals:
  - OAUTH2_CLIENT_SECRET=CHANGEME
  - SESSION_SECRET=CHANGEME

images:
- name: oryd/hydra
  newName: reaction-commerce/reaction-hydra
  newTag: latest
- name: reactioncommerce/reaction
  newTag: latest
- name: reactioncommerce/reaction-identity
  newTag: latest
- name: reactioncommerce/reaction-admin
  newTag: latest
- name: reactioncommerce/example-storefront
  newTag: latest

replicas:
- name: api-deployment
  count: 1
- name: identity-deployment
  count: 1
- name: admin-deployment
  count: 1
- name: storefront-deployment
  count: 1

namePrefix: dev-
namespace: demandcluster-dev

resources:
- ../../base

components:
- ../../components/postgresql_operator
