apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: oryd/hydra
  newTag: v1.9.0
- name: reactioncommerce/reaction
  newTag: 3.11.0
- name: reactioncommerce/identity
  newTag: 3.3.0
- name: reactioncommerce/admin
  newTag: 3.0.0-beta.11
- name: reactioncommerce/example-storefront
  newTag: 4.0.0

namePrefix: community-
namespace: demandcluster-community

resources:
- ../../base
