- op: add
  path: /spec/template/spec/containers/0/args
  value:
    - serve
    - all
    - --dangerous-force-http
    - --dangerous-allow-insecure-redirect-urls
    - http://reaction-storefront:4000/callback
