apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra-deployment
  # labels:
  #   component: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demandcluster
      # component: hydra
      release: edge
  template:
    spec:
      containers:
      - name: hydra
        image: oryd/hydra
        ports:
        - containerPort: 4444
        - containerPort: 4445
        - containerPort: 5555
        envFrom:
        - secretRef:
            name: hydra-env-secrets
        - configMapRef:
            name: hydra-env-config
#      initContainers:
#      - name: hydra-migrate
#       image: oryd/hydra
#        command:
#          - migrate
#          - sql
#          - -e
#          - -y
#        envFrom:
#          - secretRef:
#              name: hydra-env-secrets
#          - configMapRef:
#              name: hydra-env-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  # labels:
  #   component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demandcluster
      # component: api
      release: edge
  template:
    spec:
      containers:
      - name: reaction
        image: reactioncommerce/reaction
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: api-env-secrets
        - configMapRef:
            name: api-env-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  # labels:
  #   component: identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demandcluster
      # component: identity
      release: edge
  template:
    spec:
      containers:
      - name: reaction-identity
        image: reactioncommerce/identity
        ports:
        - containerPort: 4100
        envFrom:
        - secretRef:
            name: identity-env-secrets
        - configMapRef:
            name: identity-env-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  # labels:
  #   component: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demandcluster
      # component: admin
      release: edge
  template:
    spec:
      containers:
      - name: reaction-admin
        image: reactioncommerce/admin
        ports:
        - containerPort: 4080
        envFrom:
        - secretRef:
            name: admin-env-secrets
        - configMapRef:
            name: admin-env-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-deployment
  # labels:
  #   component: storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demandcluster
      # component: storefront
      release: edge
  template:
    spec:
      containers:
      - name: example-storefront
        image: reactioncommerce/example-storefront
        ports:
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: storefront-env-secrets
        - configMapRef:
            name: storefront-env-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  # labels:
  #   component: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demandcluster
      # component: mongodb
      release: edge
  template:
    spec:
      containers:
      - name: mongodb
        image: mongo:bionic
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
            name: mongo-env-secrets
        - configMapRef:
            name: mongo-env-config

